# fly.toml file generated for protohacker-ts on 2022-11-07T16:59:32Z

app = "protohacker-ts"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PROXY_ADDRESS = "chat.protohackers.com"
  PROXY_PORT = "16963"
  TCP_PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 150
    soft_limit = 75

  [[services.ports]]
    port = "10001"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
