# fly.toml file generated for protohacker-ts on 2023-01-08T12:29:30Z

app = "protohacker-ts"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  TCP_PORT = "8080"
  DEBUG = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 1100
    soft_limit = 750

  [[services.ports]]
    port = "10001"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
