# fly.toml file generated for protohacker-ts on 2022-10-15T11:28:12+01:00

app = "protohacker-ts"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  #SOCKET_ADDRESS = "fly-global-services"
  TCP_PORT = "8080"
  PROXY_ADDRESS = "chat.protohackers.com"
  PROXY_PORT = "16963"
  # UDP_PORT = "5000"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = "10001"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"

# [[services]]
#   internal_port = 5000
#   protocol = "udp"
#
#   [[services.ports]]
#     port = 5000
