# fly.toml app configuration file generated for protohacker-ts on 2023-08-11T20:50:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "protohacker-ts"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[env]
  AUTH_ADDRESS = "pestcontrol.protohackers.com"
  AUTH_PORT = "20547"
  DEBUG = "1"
  TCP_PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 10001
  [services.concurrency]
    hard_limit = 1100
    soft_limit = 750

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
