# fly.toml file generated for protohacker-ts on 2022-12-28T22:04:27Z

app = "protohacker-ts"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  SOCKET_ADDRESS = "fly-global-services"
  TCP_PORT = "8080"
  UDP_PORT = "5000"
  DEBUG = 1

[[services]]
  internal_port = 5000
  protocol = "udp"

  [[services.ports]]
    port = 5000
